### ISSUE TITLE
License Agrement

### ISSUE THREAD

**Issue by yazad3** [perenecabuto/json_schema_generator#9]
I see a reference to the license in the setup.py - but it would be in the interest of adoption that a License.txt file be added explicitly in the package clearly stating the license the code is available under.

**Comment by CodeCharm** [comment]
Agreed. This is not obvious, and not everyone is okay with just whatever the license is. It's important.

**Comment by jacobq** [comment]
@perenecabuto  Would you accept a PR that associated this project with the MIT license?

**Comment by perenecabuto** [comment]
@jacobq, Sorry for this BIG delay. I just added an MIT license to the project.

Thanks for the contribution.
